- conanfile.py
This PR updates the boost recipe for using the new cpu_count() feature during the compilation instead of using a fixed amount of cores.
Note that I have split the argument list in different lines. I do not know if this is the proper formatting style in python or not. Please, tell me if it can be improved.
> Using cpu_count() for the compilation

- conanfile.py
After the discussion we had in the PR #23, I have created this new one with the implementation in which we agreed. Now we will have one option per library indicating if the library will be compiled or not (all of them are defaulted to True, except **python**).
> Add options for compiling without each of the libraries

- conanfile.py
I suppose that overhead of `.items()` call in Python 2 can be affordable given compile time for Boost libraries.
> Fix for python 3. Call items() in dict

- conanfile.py
Using `dict.items()` instead of `dict.iteritems()` supports builds on both Python 2 and Python 3 without dependency on `six`.
> Support builds on Python 3

- .travis.yml
Hi! I noticed that there are no x86_64 binaries for macOS/apple-clang 8, so I'm adding them to CI here.
> Add missing travis pages for apple-clang 8

- conanfile.py
Currently there are some errors when using the `without_*` options with Visual Studio, with libraries that we are not building still being included in the generated `conanbuildinfo.props` file. This means that if we specify that we don't want to build particular libraries we will have to do some manual editing of the generated property file in order to get things to link.
This commit makes two changes:
1. Commit cfdb9216fadd64c3318dafe6cfbae0bb09d30d93 prevents boost libraries with non-trivial naming conventions (e.g. `math_c99`, `math_c99f`, `math_c99l`, ...) form being included when they weren't built. I've done this using substring matches (plus an exception for `prg_exec_monitor`) whcih is _OK_ for this, but not ideal.
2. Commit 4140b6c96aaef279d1d5ab6a7e047d1ecc68c9fc corrects the …
> Fix to without_* rules under VS

- conanfile.py
As Boost.IOStreams is not a header_only library there should not be a dependency to zlib and bzip2 when using `header_only=True`, see #52.
> Remove unnecessary zlib and bzip2 dep when header_only=True.

- conanfile.py
308: pos refers to the position in lib_list so cpp_info.libs needs to be at least this length.
This will leave a lot of None, but they should disappear. Otherwise a tmp list is needed and then extend that onto cpp_info.libs
> Fixing out of bound error cpp_info.libs

- README.md
When running using lower case bools in conan 1.0.4 you receive the following error:
```
error: invalid line 5: ERROR: boost/1.66.0@conan/stable: 'true' is not a valid 'options.shared' value.
error: invalid line 6: Possible values are ['False', 'True']
```
This just helps copy/paste errors from the README.md
> Upcase bools to avoid error in README.md

- .gitignore
- conanfile.py
Looks like findBoost.cmake always (even in 3.11) tries to find the pattern "boost_math" "boost_chrono".
> Try to package very simple names

- conanfile.py
Support build type RelWithDebInfo. This conan build type results in a release build of boost.
Should also work for MinRelSize, but this was not tested.
> Correct decission on boost build variant for "RelWithDebInfo".

- conanfile.py
BCP in #118 showed that Boost.Contract depends on these libraries:
`atomic, chrono, date_time, exception, system, thread`
However local testing using `without_contract=False` and the rest set to `True` concluded in only `libboost_contract` and `libboost_system` being created and needed to work.
Furthermore it didn't matter where on the `lib_list` the `contract` was put, it still linked correctly.
I prefered to stay on the safe side and left it before `exception`.
> Fix #118 - Add 'contract' to lib_list to allow explicit enabling and disabling

- .travis.yml
Last builds to be on pair with [bincrafters/conan-templates](https://github.com/bincrafters/conan-templates), which I believe is a good aim.
To minimize the load on the build server (and time), could you cancel all the unrelated builds?
> 1.66.0: Added Apple-Clang 7.3/8.1 to travis build matrix

- conanfile.py
See issue #149 
This is required when building with std > 14 for clang.
> Allow specify c++ standard when building

- conanfile.py
If the Python path in the user config jam has spaces (which is often the case on Windows if installed for all users in Program Files), Boost will fail outright. Surrounding it in quotes fixes this problem.
> Fix Python path with spaces

- conanfile.py
This fixes a bug where ldflags would be ignored.
See table 49.2 [here](https://www.boost.org/doc/libs/1_66_0/doc/html/bbv2/overview.html)
> Change ldflags to linkflags in user-config

- conanfile.py
GCC `bootstrap.sh` script requires passing the specified toolset `X` (e.g. in a conan user profile) through the option `-with-toolset`, i.e. `bootstrap.sh -with-toolset=X`. Currently, the toolset is passed as is, without specifying the option, i.e. `bootstrap X`, causing the script to ignore it and guessing the toolset from the platform.
This PR solves this bug.
> fixed selection of toolset at bootstrap

- conanfile.py
I was using RedHat 6.4 (old but still supported) and got a linker error of this kind: [\[stackoverflow\] Another “undefined reference” error when linking boost libraries](https://stackoverflow.com/questions/13653361/another-undefined-reference-error-when-linking-boost-libraries)
I don't have the original one anymore at disposal. The library I was building depended on boost_chono. One of the missing symbol was `clock_gettime`.
The issue come from the version of glibc I was using : 2.12
```
...
Link with -lrt (only for glibc versions before 2.17).
...
```
I added a check on glibc version. What do you think about it ?
> Detect glibc version and add -lrt if needed

- conanfile.py
This fixes https://github.com/conan-community/community/issues/124
> Remove signals from lib_list - Signals v1 was removed in Boost 1.69

- conanfile.py
addresses:
https://github.com/conan-community/community/issues/104
https://github.com/conan-community/community/issues/91
https://github.com/conan-community/community/issues/85
- add option to specify python executable/interpreter (default is system one)
- add option to specify python version (may be automatically deduced from python interpreter)
- use `sysconfig` module to locate python libraries and headers
~~please don't merge for a while, I gonna do some tests in the various environments first~~
(tested, everything seems to be working as expected)
(I collect various python configurations in this repository: https://github.com/SSE4/python_sysconfig_examples)
> improve python detection and configuration

- conanfile.py
Based on suggested profile for Android
https://docs.conan.io/en/latest/integrations/android_studio.html
Current `conanfile.py` will lead to `./bootstrap.sh -with-toolset=clang` and as result produce ARM executable
```
/Users/camobap/.conan/data/boost/1.69.0/conan/stable/source/boost_1_69_0/tools/build/src/engine/bootstrap/jam0: ELF 32-bit LSB pie executable ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, with debug_info, not stripped
```
> Use 'darwin' bootstrap toolchain if host os is Macos

- conanfile.py
- patches/static_object_init.patch
Doc string in boost python causes a crash in VS2017. The patch was taken from:  
https://github.com/boostorg/python/pull/208/commits/016b12e5e9e7f29f5c3ac188042fb664da255f0b
> Fix static object initialization under Visual Studio 2017

- conanfile.py
It's not possible to patch when building from install command, because we use `no_copy_source`.
conan install -r conan-community boost/1.69.0@conan/stable --build boost
> Fix conan install conan/stable --build boost

- conanfile.py
I would like to build my dependencies with a custom clang/libc++ version. By adding the `-isysroot` parameter this recipe forces my custom clang into using the libc++ provided by Xcode which fails.
The patch in this PR is a fix that works for me but it is a bit cumbersome because the using package needs to disable the additional `with_isysroot=` option when appropriate. I am open for a better idea. :) It would be great if the recipe would detect the custom clang/libc++ somehow and automagically refrain from adding `-isysroot`.
> Allow disabling automatic addition of -isysroo on macOS

- conanfile.py
Error in Building boost on windows using 'mingw_installer/1.0@conan/stable'. Bootstrap toolset is set to msvc however I'm using gcc as my compiler. **I have fixed the error** by modifying _get_boostrap_toolset() at conanfile.py as follows:
```
if tools.os_info.is_windows:
return "gcc" if self.settings.compiler == "gcc" else "" # instead of return ""
```
If you look in boost bootstrap.bat file you can find that toolset can be set to "gcc" on windows
* Package Name/Version: **boost/1.70.0@conan/stable**
* Operating System: **Windows**
* Operation System Version: **Windows 10**
* Compiler+version: **gcc-8.0**
* Conan version: **conan 1.15**
* Python version: **python 3.7.0**
* run conan install boost/1.70.0@conan/stable --build missing --profile  mingw_profile
* msvc not installed
* Use the …
> bootstrap toolset to gcc on windows, compiler=gcc

- conanfile.py
The bootstrapping step of the boost build should clear the CC and CXX variables from the environment (and probably also CFLAGS and CXXFLAGS to be safe). These might be set to a cross-compiler and its options if we're building from a cross-compilation environment, making the bootstrapper build b2 for the target architecture, which is not what we want.
> Clear CC/CXX/CFLAGS/CXXFLAGS for bootstrapping step

- conanfile.py
If one tries to build a conan package of libA overloading the following recipes
```
boost = boost/1.70.0-2@pix4d/stable
libB = libB/1.0.0@pix4d/stable
zlib = zlib/1.2.11@conan/stable
```
and if libB also depends on `boost/1.70.0-2@pix4d/stable`, one gets the following error:
```
ERROR: boost/1.70.0-2@pix4d/stable: Error in configure() method, line 104
self.requires("zlib/[>=1.2.11]@conan/stable")
ConanException: Duplicated requirement zlib/1.2.11@conan/stable != zlib/[>=1.2.11]@conan/stable
```
The problem is solved by defining requirements in the  `requirements()` method and not in the `configure()` method.
> Requirements should be defined in requirements(), not in configure()

- conanfile.py
Don't throw unknown ABI exception for mips.
> Fix cross compilation for mips arch
